### PR TITLE
Moving meta-aos revision to top of master

### PR DESCRIPTION
**Pull request by iusyk**
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>

### CODE REVIEW

**Comment by arminn** [comment]
I believe you can rebase main patch an go without merge commit "Merge branch 'master' into adopt2_258"

**Comment by rshym** [comment]
Please provide name of component in commit message. It's not clear revision of what is changed.
It's much better to use 
'Move revision of meta-aos to top commit'

Please do not use github's web UI to resolve conflicts. It results in not needed 'merge of master'. This can be easily done on local PC after fetch and rebase of your change on head of master.

**Comment by iusyk** [comment]
> I believe you can rebase main patch an go without merge commit "Merge branch 'master' into adopt2_258"

done

**Comment by iusyk** [comment]
not relevant any more - another pull request has been processed

**Pull request closed without merging**
