### PR TITLE
Added Android manifest

### PR DESCRIPTION
**Pull request by arminn**
Signed-off-by: Andrii Chepurnyi <Andrii_Chepurnyi@epam.com>

### CODE REVIEW

**Comment by andr2000** [comment]
Use epam instead of ep, doma.xml in lower case, email in signed off in lower case

**Comment by arminn** [comment]
Comments were addressed

**Comment by andr2000** [comment]
LGTM, rb

**Review by lorc — APPROVED** [review]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Pull request merged**
