### PR TITLE
Change Kernel branch to android-bsp-v0.2.2-CES2018

### PR DESCRIPTION
**Pull request by arminn**
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

### CODE REVIEW

**Comment by andr2000** [comment]
LOWER CASE PLEASE

**Comment by arminn** [comment]
@andr2000 lowercased

**Comment by andr2000** [comment]
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Review by aanisov — APPROVED** [review]
`Reviewed-by: Andrii Anisov <andrii_anisov@epam.com>`

**Pull request merged**
