### PR TITLE
Add manifest files with closed repository

### PR DESCRIPTION
**Pull request by iartemenko**
It is needed to build gen3-test product with proprietary
graphic from sources.

Signed-off-by: Iurii Artemenko <iurii_artemenko@epam.com>

### CODE REVIEW

**Comment by lorc** [comment]
s/repositor/repository

**Comment by andr2000** [comment]
Let us think if we can avoid doing src product this way

**Review by andr2000 — CHANGES_REQUESTED** [review]
if we can tell which product is built then _src.xml might not be needed

**Comment by iartemenko** [comment]
Reimplemented according to our discussion. Separate folder for "_src" product is added.

**Review by andr2000 — APPROVED** [review]

**Comment by andr2000** [comment]
`Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>`

**Pull request merged**
