### PR TITLE
Cockpitdemo protocol meta aos rev

### PR DESCRIPTION
**Pull request by iusyk**

### CODE REVIEW

**Comment by rshym** [comment]
Seems like we have some mess.

- As I understand, change of AOS repo from `remote="epam" name="epmd-aepr/meta-aos"` to `remote="github" name="aoscloud/meta-aos"` should be in second commit. At least according to message in second commit.
- The second commit has a wrong signature: `xen-troops-buildbot`.
- I'm not sure that we need to upgrade the revision of meta-clang, as I see they have changed the version to 7.1 and changed some internal repo... So if this change was tested, then OK. If not tested then may be better to keep the same revision. But I'm not sure here.

**Comment by iusyk** [comment]
> Seems like we have some mess.
> 
> * As I understand, change of AOS repo from `remote="epam" name="epmd-aepr/meta-aos"` to `remote="github" name="aoscloud/meta-aos"` should be in second commit. At least according to message in second commit.
> * The second commit has a wrong signature: `xen-troops-buildbot`.
> * I'm not sure that we need to upgrade the revision of meta-clang, as I see they have changed the version to 7.1 and changed some internal repo... So if this change was tested, then OK. If not tested then may be better to keep the same revision. But I'm not sure here.

regarding meta-clang : it is impossible to keep the old revision of meta-clang - there is a reference to the not-existed repository.

**Comment by iusyk** [comment]
> > Seems like we have some mess.
> > 
> > * As I understand, change of AOS repo from `remote="epam" name="epmd-aepr/meta-aos"` to `remote="github" name="aoscloud/meta-aos"` should be in second commit. At least according to message in second commit.
> > * The second commit has a wrong signature: `xen-troops-buildbot`.
> > * I'm not sure that we need to upgrade the revision of meta-clang, as I see they have changed the version to 7.1 and changed some internal repo... So if this change was tested, then OK. If not tested then may be better to keep the same revision. But I'm not sure here.
> 
> regarding meta-clang : it is impossible to keep the old revision of meta-clang - there is a reference to the not-existed repository.

order has been changed

**Comment by rshym** [comment]
Thanks for the explanation regarding meta-clang.

I still want to say that it's not a good idea to change aos repo in commit with the name 'replace protocol git at https'. It's better to replace aos repo in the dedicated commit.

**Comment by iusyk** [comment]
> Thanks for the explanation regarding meta-clang.
> 
> I still want to say that it's not a good idea to change aos repo in commit with the name 'replace protocol git at https'. It's better to replace aos repo in the dedicated commit.

done

**Comment by rshym** [comment]
`Acked-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>`

**Pull request merged**
